easy_admin:
    entities:        
       # List the entity class name you want to manage
        Portfolio:
            class: App\Entity\Portfolio
            label: Portfolio
            list:
                fields:
                    - id
                    - title
                    - description
                    - { property: 'image', label: 'image', type: 'image', base_path: '%app.path.uploads_images%'}
                    - link
                    - skills
            form:
                fields:
                    - title
                    - description
                    - { property: 'imageFile',  type: 'vich_image', label: 'image' }  
                    - link
                    - skills      
        Skills:
            class: App\Entity\Skills
            label: Skills
            list:
                fields:
                    - id
                    - name
                    - { property: 'logo', label: 'image', type: 'image', base_path: '%app.path.uploads_logos%'}
            form:
                fields:
                    - name
                    - { property: 'type', type: 'choice', type_options: { multiple: false, choices: { 'Frontend': 'Frontend', 'Backend': 'Backend' } } }
                    - { property: 'logoFile',  type: 'vich_image', label: 'image' }  
                    - pourcentage
                    - color
        CV: 
            class: App\Entity\CV
            label: CV
            list: 
                fields:
                    - id
                    - diplome
                    - age
                    - formationWeb
                    - parcours
            form:
                fields:
                    - diplome
                    - age
                    - formationWeb
                    - parcours