# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    filter_sets:
        # cache: ~

        # the name of the "filter set"
        small_thumb:

            # adjust the image quality to 75%
            quality: 90

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [205, 149], mode: outbound }

        # medium_thumb:

        #     quality: 95

        #     filters:
        #         # thumbnail: { size: [350, 270], mode: outbound }
        #         # use and setup the "scale" filter
        #         scale:
        #             # given 1920x1600px -> output 960x800px (relative down-scale)
        #             to: 0.08


        slider_thumb:

            # adjust the image quality to 75%
            quality: 95

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                 # use and setup the "fixed" filter
                thumbnail: { size: [1000, 500], mode: outbound }
