vich_uploader:
    db_driver: orm

    mappings:
       uploads_images:
           uri_prefix: app.path.uploads_images
           upload_destination: '%kernel.project_dir%/public%app.path.uploads_images%'